package hiendao.moviefinder.domain.model

data class TvSeries(
    val adult: Boolean,
    val backdropPath: String,
    val createdBy: String,
    val credits: List<Int>,
    val episodeRuntime: List<String>,
    val firstAirDate: String,
    val genres: List<Int>,
    val homepage: String,
    val id: Int,
    val images: List<String>,
    val inProduction: Boolean,
    val languages: List<String>,
    val lastAirDate: String,
    val lastEpisodeToAir: String,
    val name: String,
    val networks: List<String>,
    val nextEpisodeToAir: String,
    val numberOfEpisodes: Int,
    val numberOfSeasons: Int,
    val originCountry: List<String>,
    val originalLanguage: String,
    val originalName: String,
    val overview: String,
    val popularity: Double,
    val posterPath: String,
    val productionCompanies: List<String>,
    val productionCountries: List<String>,
    val seasons: List<Int>,
    val spokenLanguages: List<String>,
    val status: String,
    val tagline: String,
    val type: String,
    val videos: List<String>,
    val similar: List<Int>,
    val voteAverage: Double,
    val voteCount: Int,
    val addedToFavorite: Boolean = false,
)
